-- 코드를 작성해주세요
SELECT ID
    , CASE
        WHEN A.COLONY_LEVEL = 1 THEN 'CRITICAL'
        WHEN A.COLONY_LEVEL = 2 THEN 'HIGH'
        WHEN A.COLONY_LEVEL = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END COLONY_NAME
FROM (
    SELECT ID
        , NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) COLONY_LEVEL
    FROM ECOLI_DATA
) A
ORDER BY A.ID;