-- 코드를 입력하세요
# SELECT ANIMAL_ID, outs.NAME
# FROM ANIMAL_OUTS outs
# LEFT JOIN ANIMAL_INS ins
# USING (ANIMAL_ID)
# WHERE INTAKE_CONDITION IS NULL
# ORDER BY ANIMAL_ID;

SELECT ANIMAL_ID, O.NAME
FROM ANIMAL_INS I
RIGHT JOIN ANIMAL_OUTS O
USING (ANIMAL_ID)
WHERE I.DATETIME IS NULL
ORDER BY ANIMAL_ID;