-- 코드를 입력하세요
# SELECT ins.NAME, ins.DATETIME
# FROM ANIMAL_INS ins
# LEFT JOIN ANIMAL_OUTS outs
# USING (ANIMAL_ID)
# WHERE outs.DATETIME IS NULL
# ORDER BY ins.DATETIME
# LIMIT 3;

SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (
                            SELECT ANIMAL_ID
                            FROM ANIMAL_OUTS
                        )
ORDER BY DATETIME
LIMIT 3;