# SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
# FROM ANIMAL_INS
#     JOIN ANIMAL_OUTS
#     ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
# WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
# ORDER BY ANIMAL_INS.DATETIME;

SELECT ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
USING (ANIMAL_ID)
WHERE O.DATETIME < I.DATETIME
ORDER BY I.DATETIME;